### PR TITLE
Correctly starting Selenoid from image with custom registry host and …

### LINKED ISSUE #250: Failed to start: Selenoid with registry if dont run docker pull
Hello!
```
cm_linux_amd64 selenoid start --browsers android:4.4  --registry https://docker-registry.tools.myteam.ru:10443
> Using Docker
- Your Docker API version is 1.39
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://docker-registry.tools.myteam.ru:10443/v2/
registry.tags url=https://docker-registry.tools.myteam.ru:10443/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image docker-registry.tools.myteam.ru:10443/aerokube/selenoid:1.9.3
> Configuring Selenoid...
> Processing browser "android"...
- Fetching tags for image selenoid/android
registry.tags url=https://docker-registry.tools.myteam.ru:10443/v2/selenoid/android/tags/list repository=selenoid/android
- Pulling image docker-registry.tools.myteam.ru:10443/selenoid/android:4.4
> Pulling video recorder image...
- Pulling image docker-registry.tools.myteam.ru:10443/selenoid/video-recorder:latest-release
> Configuration saved to /root/.aerokube/selenoid/browsers.json
> Starting Selenoid...
x Failed to start: Selenoid image is not downloaded: this is probably a bug
```

```
docker inspect selenoid
[]
Error: No such object: selenoid
```

```
docker kill -s HUP selenoid
Error response from daemon: Cannot kill container: selenoid: No such container: selenoid
```

```
sestatus 
SELinux status:                 disabled
```

```
/usr/local/bin/aerokube-cm selenoid start --vnc --force --browsers android:4.4  --registry https://docker-registry.tools.myteam.ru:10443
> Using Docker
- Your Docker API version is 1.39
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://docker-registry.tools.myteam.ru:10443/v2/
registry.tags url=https://docker-registry.tools.myteam.ru:10443/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image docker-registry.tools.myteam.ru:10443/aerokube/selenoid:1.9.3
> Configuring Selenoid...
> Processing browser "android"...
- Fetching tags for image selenoid/android
registry.tags url=https://docker-registry.tools.myteam.ru:10443/v2/selenoid/android/tags/list repository=selenoid/android
- Requested to download VNC images...
- Pulling image docker-registry.tools.myteam.ru:10443/selenoid/vnc_android:4.4
> Pulling video recorder image...
- Pulling image docker-registry.tools.myteam.ru:10443/selenoid/video-recorder:latest-release
> Configuration saved to /root/.aerokube/selenoid/browsers.json
> Starting Selenoid...
x Failed to start: Selenoid image is not downloaded: this is probably a bug
```

### PR DESCRIPTION
**Pull request by vania-pooh**
…port (fixes #250)

### CODE REVIEW

File: selenoid/docker.go [hunk 1]
```diff
@@ -261,6 +261,7 @@ func (c *DockerConfigurator) getImage(name string, version string) *types.ImageS
 		c.Errorf("Failed to list images: %v", err)
 		return nil
 	}
+	//name = c.getFullyQualifiedImageRef(name)
```
Comment (lanwen) [inline selenoid/docker.go]: what it suppose to mean?

Comment (vania-pooh) [reply selenoid/docker.go]: Hmm, accidentally commented stuff. Need to recheck.
